runtime: python311
entrypoint: gunicorn -b :$PORT main:app
instance_class: F1

automatic_scaling:
  max_instances: 1
  min_instances: 0
  target_cpu_utilization: 0.65

env_variables:
  SECRET_KEY: '51d32510bca5950c17a81ba979a2e02aedf502081c3d173a7948f89063aaeb0f'
  FLASK_ENV: 'production'
  
handlers:
- url: /static
  static_dir: BelarminoMonteiroAdvogado/static
  secure: always
  expiration: "1d"
  
- url: /.*
  script: auto
  secure: always
