:: filepath: d:\PROJETOS PYTHON 2025\BelarminoMonteiroAdvogado\stamp_db.bat
@echo off
REM ...existing code...

echo [INFO] Executando auto_fix.py (reparador) antes do stamp...
python auto_fix.py
if errorlevel 1 (
    echo [WARN] auto_fix.py retornou erro; ainda assim tentando 'flask db stamp head'...
    flask db stamp head || echo [ERROR] flask db stamp head falhou.
) else (
    echo [INFO] auto_fix.py concluido. Executando 'flask db stamp head'...
    flask db stamp head || echo [WARN] flask db stamp head retornou erro.
)

REM ...existing code...