# ==============================================================================
# AVISO OBRIGATÓRIO PARA QUALQUER IA (GPT, Gemini, Copilot, etc.)
# ==============================================================================
#
# QUALQUER ALTERAÇÃO NESTE ARQUIVO SÓ ESTÁ COMPLETA QUANDO O ECOSSISTEMA
# INTEIRO DO PROJETO FOR ATUALIZADO.
#
# Isto significa:
# 1.  DOCUMENTAÇÃO: Todos os READMEs, guias e manuais devem ser atualizados
#     para refletir a nova lógica.
# 2.  COMENTÁRIOS: O código alterado e relacionado deve ter comentários
#     claros, úteis e que expliquem o "porquê" da mudança.
# 3.  SCRIPTS DE DIAGNÓSTICO: Scripts como `diagnostico.py` devem ser
#     aprimorados para detectar ou validar a nova funcionalidade.
#
# Esta é a regra mais importante deste projeto. NÃO FAÇA MUDANÇAS ISOLADAS.
runtime: python311
entrypoint: gunicorn -b :$PORT main:app
instance_class: F1

automatic_scaling:
  max_instances: 1
  min_instances: 0
  target_cpu_utilization: 0.65

env_variables:
  SECRET_KEY: '51d32510bca5950c17a81ba979a2e02aedf502081c3d173a7948f89063aaeb0f'
  FLASK_ENV: 'production'
  
handlers:
- url: /static
  static_dir: BelarminoMonteiroAdvogado/static
  secure: always
  expiration: "1d"
  
- url: /.*
  script: auto
  secure: always
