runtime: python311
entrypoint: gunicorn -b :$PORT main:app
instance_class: F1

automatic_scaling:
  max_instances: 1
  min_instances: 0
  target_cpu_utilization: 0.65

env_variables:
  SECRET_KEY: 'e851374856e95ba033620eb7a2346914190e37b2210fab2f3798074d5a84e16b'
  FLASK_ENV: 'production'
  CDN_URL: 'https://storage.googleapis.com/belarmino-advogado-videos'
  
handlers:
- url: /static
  static_dir: BelarminoMonteiroAdvogado/static
  secure: always
  expiration: "1d"
  
- url: /.*
  script: auto
  secure: always
